name: Update workflow
on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 * * 2-5'
    - cron:  '0 9 * * 1'
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Update job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Get python dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: backend/requirements.txt
      - run: mkdir build
      - run: python backend/main.py ka > build/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
          clean: false
